// The generated client schema + its DRIFT GATE.
//
// The committed artifact (schema/context-client-schema.json) is what downstream client generators
// consume — e05's JS client above all. It is generated from the ONE registry, never hand-edited, so
// this test fails the moment the two disagree: change the contract, re-run the build (the custom
// command regenerates it), commit the regenerated artifact. That is the whole point — a hand-written
// client typing drifts silently; a generated one with this gate cannot.

#include "context/editor/client/schema.h"

#include "client_test.h"

#include <fstream>
#include <iostream>
#include <sstream>
#include <string>

#ifndef CONTEXT_CLIENT_SCHEMA_COMMITTED
#error "CONTEXT_CLIENT_SCHEMA_COMMITTED (path to the committed schema) must be defined by the build."
#endif

using context::editor::client::client_schema;
using context::editor::client::client_schema_text;
using context::editor::contract::Json;

namespace
{
std::string read_file(const std::string& path)
{
    std::ifstream f(path, std::ios::binary);
    if (!f)
        return std::string();
    std::ostringstream ss;
    ss << f.rdbuf();
    return ss.str();
}

// The schema carries what a client actually needs to talk to the daemon.
void test_schema_has_the_client_sections()
{
    const Json schema = client_schema();
    CHECK(schema.is_object());
    CHECK(schema.contains("schemaVersion"));
    CHECK(schema.contains("protocolMajor"));
    for (const char* section :
         {"protocol", "rpcMethods", "eventTopics", "eventEnvelope", "subscription", "errorCatalog"})
        CHECK(schema.contains(std::string(section)));

    // The subscription protocol the consumer implements is described here, so a generated client
    // can be checked against it.
    CHECK(schema.at("subscription").at("snapshotThenDelta").as_bool());
    CHECK(schema.at("eventTopics").size() > 0);
    CHECK(schema.at("rpcMethods").size() > 0);

    // The OTHER doors onto the same registry are deliberately NOT projected — a client binding has
    // no use for the CLI verb grammar or the MCP tool surface, and carrying them would make every
    // unrelated CLI change look like client-contract drift.
    CHECK(!schema.contains("verbs"));
    CHECK(!schema.contains("coreFlags"));
    CHECK(!schema.contains("mcpTools"));
}

// Determinism: the same registry must project the same bytes every time, or the drift gate would
// flap and the artifact would be unreviewable.
void test_schema_text_is_deterministic()
{
    // Two INDEPENDENT projections must agree — that comparison is the assertion, so it genuinely
    // needs both calls. The remaining checks reuse the first result rather than re-projecting the
    // whole registry (and re-dumping ~4200 lines) two more times to inspect the same string.
    const std::string text = client_schema_text();
    CHECK(text == client_schema_text());
    CHECK(!text.empty());
    CHECK(text.back() == '\n');
}

void test_committed_artifact_matches_the_generated_one()
{
    const std::string committed = read_file(CONTEXT_CLIENT_SCHEMA_COMMITTED);
    const std::string generated = client_schema_text();
    const bool matches = committed == generated;
    if (!matches)
    {
        std::cerr << "\n*** client schema DRIFT ***\n"
                  << "The committed artifact no longer matches what the contract registry projects.\n"
                  << "Fix: build the `context_client_schema` target, then copy the regenerated\n"
                  << "     file over " << CONTEXT_CLIENT_SCHEMA_COMMITTED << " and commit it.\n"
                  << "committed bytes=" << committed.size() << " generated bytes=" << generated.size()
                  << "\n\n";
    }
    CHECK(matches);
}
} // namespace

int main()
{
    test_schema_has_the_client_sections();
    test_schema_text_is_deterministic();
    test_committed_artifact_matches_the_generated_one();
    CLIENT_TEST_MAIN_END();
}
