#!/usr/bin/env python3
"""Embed a binary file as a C++ byte-array translation unit (build-time bin2c).

The M7 runtime-UI text substrate ships its default fonts EMBEDDED (compiled-in, no runtime file IO —
the R-SEC-006 trust boundary: embedded trusted fonts only). This generator turns a vendored `.ttf`
into a `.cpp` the text package compiles, so the fonts are byte-for-byte the vendored artifacts with no
path resolution and no asset loading.

Usage:
    embed_bin.py <input-binary> <output.cpp> <symbol> [--namespace NS]

Emits a TU defining, with EXTERNAL linkage (namespace-scope `const` is internal linkage by default, so
`extern` + an initializer is required for a matching `extern const unsigned char <symbol>[];`
declaration in a hand-written header to link):

    namespace <NS>
    {
    extern const unsigned char <symbol>[] = { 0x.., ... };
    extern const unsigned long <symbol>_len = <N>u;
    }

Deterministic: fixed byte order, fixed lowercase-hex formatting, fixed wrap width — the generated TU is
stable across platforms and Python versions, so a rebuild never spuriously dirties the build.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

_BYTES_PER_LINE = 20
_DEFAULT_NAMESPACE = "context::packages::ui::text::detail"


def render(data: bytes, symbol: str, namespace: str) -> str:
    """Return the full C++ source text embedding `data` under `symbol` in `namespace`."""
    out: list[str] = []
    out.append("// Generated by tools/embed_bin.py — DO NOT EDIT (regenerate from the vendored source).")
    out.append(f"namespace {namespace}")
    out.append("{")
    out.append(f"extern const unsigned char {symbol}[] = {{")
    if data:
        for i in range(0, len(data), _BYTES_PER_LINE):
            chunk = data[i : i + _BYTES_PER_LINE]
            out.append("    " + ",".join(f"0x{b:02x}" for b in chunk) + ",")
    else:
        # A zero-length array is ill-formed in standard C++; emit one padding byte that `_len == 0`
        # makes unreachable (consumers size the span from `_len`, never from sizeof).
        out.append("    0x00,")
    out.append("};")
    out.append(f"extern const unsigned long {symbol}_len = {len(data)}u;")
    out.append(f"}} // namespace {namespace}")
    return "\n".join(out) + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Embed a binary file as a C++ byte array.")
    ap.add_argument("input", help="input binary file")
    ap.add_argument("output", help="output .cpp path")
    ap.add_argument("symbol", help="C++ identifier for the generated array")
    ap.add_argument("--namespace", default=_DEFAULT_NAMESPACE, help="enclosing namespace")
    args = ap.parse_args(argv)

    data = Path(args.input).read_bytes()
    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render(data, args.symbol, args.namespace), encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
